const SUBJECTS = {
  // Classes 9-12 (No semesters)
  9: [
    "Mathematics",
    "Science",
    "English",
    "Social Science",
    "Hindi",
    "Sanskrit",
  ],
  10: [
    "Mathematics",
    "Science",
    "English",
    "Social Science",
    "Hindi",
    "Sanskrit",
    "IT",
  ],
  11: [
    "Physics",
    "Chemistry",
    "Mathematics",
    "Biology",
    "English",
    "Economics",
    "Accountancy",
    "Business Studies",
    "History",
    "Geography",
    "Political Science",
  ],
  12: [
    "Physics",
    "Chemistry",
    "Mathematics",
    "Biology",
    "English",
    "Economics",
    "Accountancy",
    "Business Studies",
    "History",
    "Geography",
    "Political Science",
    "Computer Science",
  ],

  // Bachelor Degrees (Semester-Wise)
  "B.Tech": {
    "Sem 1": [
      "Eng Math I",
      "Eng Physics",
      "Basic Electrical",
      "Eng Graphics",
      "C Programming",
    ],
    "Sem 2": [
      "Eng Math II",
      "Eng Chemistry",
      "Basic Electronics",
      "Mechanics",
      "Data Structures",
    ],
    "Sem 3": [
      "Eng Math III",
      "Digital Logic",
      "OOP using C++",
      "Discrete Math",
      "Network Theory",
    ],
    "Sem 4": [
      "Computer Organization",
      "Database Mgt (DBMS)",
      "OS",
      "Design & Analysis of Algo",
      "Microprocessors",
    ],
    "Sem 5": [
      "Computer Networks",
      "Software Engg",
      "Theory of Computation",
      "Web Technology",
    ],
    "Sem 6": ["Compiler Design", "AI", "Machine Learning", "Computer Graphics"],
    "Sem 7": [
      "Cloud Computing",
      "Cryptography",
      "Distributed Systems",
      "Data Mining",
    ],
    "Sem 8": ["Major Project", "IoT", "Blockchain", "Big Data Analytics"],
  },
  "B.Tech (CSE)": {
    "Sem 1": ["Eng Math I", "Eng Physics", "C Programming"],
    "Sem 2": ["Eng Math II", "Eng Chemistry", "Data Structures"],
    "Sem 3": ["OOP", "Digital Logic", "Discrete Math"],
    "Sem 4": ["DBMS", "OS", "Algo Design"],
    "Sem 5": ["Computer Networks", "Software Engg", "Theory of Computation"],
    "Sem 6": ["Compiler Design", "Advanced Web", "Data Mining"],
    "Sem 7": ["Cloud Computing", "Cyber Security", "AI"],
    "Sem 8": ["Capstone Project", "Blockchain"],
  },
  "B.Tech (AI & DS)": {
    "Sem 1": ["Eng Math I", "Physics", "C Programming"],
    "Sem 2": ["Eng Math II", "Data Structures", "Python"],
    "Sem 3": ["Math for AI", "DBMS", "Machine Learning Intro"],
    "Sem 4": ["OS", "Deep Learning", "Algo Design"],
    "Sem 5": ["Data Analytics", "NLP", "Computer Vision"],
    "Sem 6": ["Big Data", "Reinforcement Learning", "Cloud Computing"],
    "Sem 7": ["AI Ethics", "Robotics", "Data Visualization"],
    "Sem 8": ["Project", "Advanced AI"],
  },
  "B.Tech (CyberSec)": {
    "Sem 1": ["Eng Math I", "Physics", "C Programming"],
    "Sem 2": ["Eng Math II", "Data Structures", "Computer Networks"],
    "Sem 3": ["OOP", "Network Security", "Discrete Math"],
    "Sem 4": ["DBMS", "OS", "Information Security"],
    "Sem 5": ["Cryptography", "Ethical Hacking", "Software Security"],
    "Sem 6": ["Digital Forensics", "Cyber Law", "Vulnerability Assessment"],
    "Sem 7": ["Malware Analysis", "Cloud Security", "Incident Response"],
    "Sem 8": ["Capstone Project", "Security Auditing"],
  },
  "B.Sc": {
    "Sem 1": ["Mechanics", "Calculus", "Inorganic Chemistry"],
    "Sem 2": ["Electromagnetism", "Algebra", "Organic Chemistry"],
    "Sem 3": ["Thermodynamics", "Real Analysis", "Physical Chemistry"],
    "Sem 4": ["Optics", "Differential Eq", "Analytical Chemistry"],
    "Sem 5": ["Quantum Mechanics", "Linear Algebra", "Spectroscopy"],
    "Sem 6": ["Solid State Physics", "Numerical Methods", "Project"],
  },
  "B.Com": {
    "Sem 1": ["Financial Account I", "Business Org", "Micro Economics"],
    "Sem 2": ["Financial Account II", "Business Math", "Macro Economics"],
    "Sem 3": ["Corporate Account", "Company Law", "Income Tax Law"],
    "Sem 4": ["Cost Account", "Business Comm", "Indirect Tax"],
    "Sem 5": ["Auditing", "Financial Mgt", "Enterpreneurship"],
    "Sem 6": ["Mgt Account", "Business Environment", "Project"],
  },
  "B.Com (Hons)": {
    "Sem 1": ["Advanced Financial Account", "Business Org", "Micro Economics"],
    "Sem 2": ["Corporate Account I", "Business Law", "Macro Economics"],
    "Sem 3": ["Corporate Account II", "Company Law", "Cost Account"],
    "Sem 4": ["Income Tax Law", "Business Stats", "Financial Mgt"],
    "Sem 5": ["Auditing", "Strategic Mgt", "Enterpreneurship"],
    "Sem 6": ["Investment Mgt", "Business Environment", "Project"],
  },
  "B.A": {
    "Sem 1": ["History I", "Pol Science I", "English I"],
    "Sem 2": ["History II", "Pol Science II", "English II"],
    "Sem 3": ["History III", "Pol Science III", "Economics I"],
    "Sem 4": ["History IV", "Pol Science IV", "Economics II"],
    "Sem 5": ["History V", "International Relations", "Sociology I"],
    "Sem 6": ["History VI", "Public Admin", "Sociology II"],
  },
  BCA: {
    "Sem 1": ["C Programming", "Maths I", "IT Fundamentals"],
    "Sem 2": ["Data Structures", "Maths II", "Digital Electronics"],
    "Sem 3": ["C++", "Computer Org", "DBMS"],
    "Sem 4": ["Java", "OS", "Software Engg"],
    "Sem 5": ["Python", "Computer Networks", "Web Tech"],
    "Sem 6": ["Android Dev", "E-Commerce", "Project"],
  },
  "BCA (AI & ML)": {
    "Sem 1": ["C Programming", "Maths for AI", "IT Fundamentals"],
    "Sem 2": ["Data Structures", "Python Basics", "Stats"],
    "Sem 3": ["Intro to AI", "DBMS", "Machine Learning 101"],
    "Sem 4": ["Java", "Deep Learning", "Data Analysis"],
    "Sem 5": ["NLP", "Computer Networks", "Web Tech"],
    "Sem 6": ["AI Project", "Ethics in AI", "Big Data"],
  },
  "BCA (DS)": {
    "Sem 1": ["C Programming", "Maths I", "Stats I"],
    "Sem 2": ["Data Structures", "Python", "Stats II"],
    "Sem 3": ["DBMS", "Data Mining", "Data Visualization"],
    "Sem 4": ["R Programming", "Big Data", "OS"],
    "Sem 5": ["Machine Learning", "Cloud Computing", "Web Tech"],
    "Sem 6": ["Data Science Project", "Business Analytics", "AI Basics"],
  },
  BBA: {
    "Sem 1": ["Prin of Mgt", "Business English", "Financial Account"],
    "Sem 2": ["Org Behavior", "Business Math", "Macro Econ"],
    "Sem 3": ["Marketing Mgt", "Business Law", "HR Mgt"],
    "Sem 4": ["Financial Mgt", "Research Methods", "Operations Mgt"],
    "Sem 5": ["Strategic Mgt", "Enterpreneurship", "Consumer Behavior"],
    "Sem 6": ["Intl Business", "Project", "Business Ethics"],
  },
  "BBA (Finance)": {
    "Sem 1": ["Prin of Mgt", "Business English", "Financial Account"],
    "Sem 2": ["Org Behavior", "Business Math", "Macro Econ"],
    "Sem 3": ["Corporate Finance", "Business Law", "Financial Markets"],
    "Sem 4": ["Financial Mgt", "Taxation", "Investment Analysis"],
    "Sem 5": ["Derivatives", "Banking", "Risk Mgt"],
    "Sem 6": ["Portfolio Mgt", "Finance Project", "Business Ethics"],
  },
  "BBA (Marketing)": {
    "Sem 1": ["Prin of Mgt", "Business English", "Financial Account"],
    "Sem 2": ["Org Behavior", "Business Math", "Macro Econ"],
    "Sem 3": ["Marketing Mgt", "Business Law", "Consumer Behavior"],
    "Sem 4": ["Digital Marketing", "Research Methods", "Brand Mgt"],
    "Sem 5": ["Retail Mgt", "Sales Mgt", "Advertising"],
    "Sem 6": ["Intl Marketing", "Marketing Project", "Business Ethics"],
  },
  BDS: {
    "Sem 1": ["General Anatomy", "Physiology"],
    "Sem 2": ["Biochemistry", "Dental Anatomy"],
    "Sem 3": ["Dental Materials", "Pharmacology"],
    "Sem 4": ["Pathology", "Microbiology"],
    "Sem 5": ["General Medicine", "General Surgery"],
    "Sem 6": ["Oral Pathology", "Microbiology Part 2"],
    "Sem 7": ["Public Health Dentistry", "Periodontology"],
    "Sem 8": ["Orthodontics", "Oral Surgery"],
  },
  BHM: {
    "Sem 1": ["Food Prod I", "F&B Service I", "Front Office I"],
    "Sem 2": ["Food Prod II", "F&B Service II", "Accommodation I"],
    "Sem 3": ["Food Prod III", "F&B Service III", "Front Office II"],
    "Sem 4": ["Industrial Training Phase I"],
    "Sem 5": ["Advanced Food Prod", "Advanced F&B", "Accommodation II"],
    "Sem 6": ["F&B Mgt", "Facility Planning", "Financial Mgt"],
    "Sem 7": ["Hospitality Marketing", "Tourism", "HR Mgt"],
    "Sem 8": ["Industrial Training Phase II"],
  },
  BPT: {
    "Sem 1": ["Anatomy I", "Physiology I", "Biochemistry"],
    "Sem 2": ["Anatomy II", "Physiology II", "Biomechanics"],
    "Sem 3": ["Pathology", "Microbiology", "Psychology"],
    "Sem 4": ["Pharmacology", "Exercise Therapy I", "Electrotherapy I"],
    "Sem 5": ["Exercise Therapy II", "Electrotherapy II", "Orthopedics"],
    "Sem 6": ["General Medicine", "General Surgery", "Pediatrics"],
    "Sem 7": ["PT in Ortho", "PT in Neuro", "PT in Cardio"],
    "Sem 8": ["Rehabilitation", "Research Ethics", "Project"],
  },
  "B.V.Sc": {
    "Sem 1": ["Vet Anatomy", "Vet Physiology"],
    "Sem 2": ["Vet Biochemistry", "Animal Extension Educ"],
    "Sem 3": ["Vet Pathology", "Vet Microbiology"],
    "Sem 4": ["Vet Parasitology", "Vet Pharmacology"],
    "Sem 5": ["Vet Public Health", "Vet Epidemiology"],
    "Sem 6": ["Animal Genetics", "Animal Nutrition"],
    "Sem 7": ["Livestock Prod Mgt", "Vet Surgery"],
    "Sem 8": ["Vet Medicine", "Vet Gynaecology"],
  },
  "B.F.A": {
    "Sem 1": ["Drawing I", "Painting I", "History of Art I"],
    "Sem 2": ["Drawing II", "Painting II", "History of Art II"],
    "Sem 3": ["Sculpture I", "Applied Art I", "Aesthetics I"],
    "Sem 4": ["Sculpture II", "Applied Art II", "Aesthetics II"],
    "Sem 5": ["Printmaking I", "Composition I", "Modern Art"],
    "Sem 6": ["Printmaking II", "Composition II", "Indian Art"],
    "Sem 7": ["Specialization Studio", "Exhibition Design"],
    "Sem 8": ["Portfolio", "Final Display"],
  },
  BMS: {
    "Sem 1": ["Intro to Business", "Business Math", "Econ I"],
    "Sem 2": ["Business Comm", "Econ II", "Financial Account"],
    "Sem 3": ["Marketing Mgt", "Cost Account", "Business Law"],
    "Sem 4": ["HR Mgt", "Financial Mgt", "Org Behavior"],
    "Sem 5": ["Strategic Mgt", "Logistics Mgt", "Ethics"],
    "Sem 6": ["Project", "Enterpreneurship", "Operations Mgt"],
  },
  BAMS: {
    "Sem 1": ["Padartha Vigyan I", "Ayurved Itihas", "Sanskrit"],
    "Sem 2": ["Padartha Vigyan II", "Rachana Sharir I", "Kriya Sharir I"],
    "Sem 3": ["Rachana Sharir II", "Kriya Sharir II", "Astanga Hridaya"],
    "Sem 4": ["Dravyaguna Vigyan I", "Agad Tantra"],
    "Sem 5": ["Dravyaguna Vigyan II", "Rasashastra I"],
    "Sem 6": ["Rasashastra II", "Roga Nidan I"],
    "Sem 7": ["Roga Nidan II", "Swasthavritta I"],
    "Sem 8": ["Swasthavritta II", "Prasuti Tantra"],
    "Sem 9": ["Kaumarbhritya", "Kayachikitsa"],
  },
  BHMS: {
    "Sem 1": ["Anatomy I", "Physiology I", "Homoeo Pharmacy I"],
    "Sem 2": ["Anatomy II", "Physiology II", "Homoeo Pharmacy II"],
    "Sem 3": ["Pathology I", "Materia Medica I", "Organon I"],
    "Sem 4": ["Pathology II", "Materia Medica II", "Organon II"],
    "Sem 5": ["Surgery I", "Gynaecology I", "Materia Medica III"],
    "Sem 6": ["Surgery II", "Gynaecology II", "Organon III"],
    "Sem 7": ["Practice of Med I", "Community Med I"],
    "Sem 8": ["Practice of Med II", "Community Med II"],
  },
  "M.Tech": {
    "Sem 1": ["Advanced Algo", "Advanced Math", "Elective I"],
    "Sem 2": ["Data Science", "Machine Learning", "Elective II"],
    "Sem 3": ["Pre-Dissertation", "Seminar"],
    "Sem 4": ["Dissertation", "Final Viva"],
  },
  "M.Sc": {
    "Sem 1": ["Advanced Physics I", "Advanced Chemistry", "Math Methods"],
    "Sem 2": ["Quantum Mech I", "Stat Physics", "Lab I"],
    "Sem 3": ["Solid State Phys", "Nuclear Phys", "Lab II"],
    "Sem 4": ["Project", "Elective"],
  },
  "M.Com": {
    "Sem 1": ["Adv Financial Acct", "Managerial Econ", "Org Behavior"],
    "Sem 2": ["Corporate Finance", "Marketing Mgt", "HR Mgt"],
    "Sem 3": ["Strategic Mgt", "Direct Taxes", "Security Analysis"],
    "Sem 4": ["Intl Business", "Project", "Indirect Taxes"],
  },
  "M.A": {
    "Sem 1": ["Literature I", "History Intro", "Pol Theory"],
    "Sem 2": ["Literature II", "World History", "Intl Rel"],
    "Sem 3": ["Modern Lit", "Indian History", "Pub Admin"],
    "Sem 4": ["Postcolonial Lit", "Project", "Sociology"],
  },
  MCA: {
    "Sem 1": ["C++ Prog", "Computer Org", "Discrete Math"],
    "Sem 2": ["Data Structures", "DBMS", "OS"],
    "Sem 3": ["Java Prog", "Software Engg", "Computer Networks"],
    "Sem 4": ["Web Tech", "AI", "Project"],
  },
  MBA: {
    "Sem 1": ["Mgt Concepts", "Managerial Econ", "Financial Acct"],
    "Sem 2": ["Marketing Mgt", "HR Mgt", "Financial Mgt"],
    "Sem 3": ["Strategic Mgt", "Supply Chain Mgt", "Elective I"],
    "Sem 4": ["Business Law", "Project", "Elective II"],
  },
  "MBA (Finance)": {
    "Sem 1": ["Mgt Concepts", "Managerial Econ", "Financial Acct"],
    "Sem 2": ["Marketing Mgt", "HR Mgt", "Financial Mgt"],
    "Sem 3": ["Corporate Finance", "Investment Analysis", "Taxation"],
    "Sem 4": ["Portfolio Mgt", "Derivatives", "Project"],
  },
  "MBA (Marketing)": {
    "Sem 1": ["Mgt Concepts", "Managerial Econ", "Financial Acct"],
    "Sem 2": ["Marketing Mgt", "HR Mgt", "Financial Mgt"],
    "Sem 3": ["Consumer Behavior", "Brand Mgt", "Digital Marketing"],
    "Sem 4": ["Retail Mgt", "Sales Mgt", "Project"],
  },
  "MBA (HR)": {
    "Sem 1": ["Mgt Concepts", "Managerial Econ", "Financial Acct"],
    "Sem 2": ["Marketing Mgt", "HR Mgt", "Financial Mgt"],
    "Sem 3": ["HR Planning", "Performance Mgt", "Labor Laws"],
    "Sem 4": ["Compensation Mgt", "Org Development", "Project"],
  },
  MD: {
    "Sem 1": ["Basic Sciences", "Applied Anatomy"],
    "Sem 2": ["Clinical Methods", "Genetics"],
    "Sem 3": ["Internal Medicine I", "Pediatrics I"],
    "Sem 4": ["Internal Medicine II", "Thesis Work"],
  },
  MS: {
    "Sem 1": ["Surgical Anatomy", "Basic Surgical Skills"],
    "Sem 2": ["Gen Surgery I", "Ortho Basics"],
    "Sem 3": ["Gen Surgery II", "Elective Surgery"],
    "Sem 4": ["Advanced Surgery", "Thesis Work"],
  },
  LLM: {
    "Sem 1": ["Law & Social Trans", "Indian Const Law"],
    "Sem 2": ["Judicial Process", "Legal Educ & Research"],
    "Sem 3": ["Corporate Law", "Criminal Law"],
    "Sem 4": ["Dissertation", "Viva"],
  },
  "M.Ed": {
    "Sem 1": ["Philosophy of Educ", "Sociology of Educ"],
    "Sem 2": ["Educational Psych", "Research Methods"],
    "Sem 3": ["Educational Admin", "Curriculum Dev"],
    "Sem 4": ["Dissertation", "Special Educ"],
  },
  "M.Des": {
    "Sem 1": ["Design Research", "Visual Dynamics"],
    "Sem 2": ["Advanced Product Design", "Interaction Design"],
    "Sem 3": ["Design Management", "Sustainable Design"],
    "Sem 4": ["Final Project", "Portfolio"],
  },
  "M.Arch": {
    "Sem 1": ["Adv Arch Design I", "Urban Design"],
    "Sem 2": ["Adv Arch Design II", "Sustainable Arch"],
    "Sem 3": ["Housing", "Landscape Arch"],
    "Sem 4": ["Thesis", "Professional Practice"],
  },
  "M.Pharm": {
    "Sem 1": ["Modern Pharm Analysis", "Drug Delivery Sys"],
    "Sem 2": ["Adv Biopharm", "Computer Aided Drug Design"],
    "Sem 3": ["Research Methodology", "Pre-Dissertation"],
    "Sem 4": ["Dissertation", "Viva"],
  },
  CA: {
    Foundation: [
      "Accounting",
      "Business Laws",
      "Quant Aptitude",
      "Business Econ",
    ],
    Intermediate: [
      "Advanced Acct",
      "Corporate Laws",
      "Taxation",
      "Costing",
      "Auditing",
      "Financial Mgt",
    ],
    Final: [
      "Financial Reporting",
      "Adv Financial Mgt",
      "Adv Auditing",
      "Direct Tax",
      "Indirect Tax",
      "IBS",
    ],
  },
  LLB: {
    "Sem 1": ["Jurisprudence", "Contract I", "Family Law I"],
    "Sem 2": ["Contract II", "Family Law II", "Constitutional Law I"],
    "Sem 3": ["Constitutional Law II", "Criminal Law I", "Company Law"],
    "Sem 4": ["Criminal Law II", "Property Law", "Admin Law"],
    "Sem 5": ["Civil Proc Code", "Evidence Law", "Env Law"],
    "Sem 6": ["Labor Law", "Taxation Law", "Moot Court"],
  },
  MBBS: {
    "Phase I": ["Anatomy", "Physiology", "Biochemistry"],
    "Phase II": ["Pathology", "Microbiology", "Pharmacology"],
    "Phase III Part 1": [
      "Forensic Med",
      "Community Med",
      "ENT",
      "Opthalmology",
    ],
    "Phase III Part 2": [
      "Gen Medicine",
      "Gen Surgery",
      "Pediatrics",
      "Obstetrics",
    ],
  },
  "B.Arch": {
    "Sem 1": ["Arch Design I", "Bldg Construction I", "Graphics I"],
    "Sem 2": ["Arch Design II", "Bldg Construction II", "Graphics II"],
    "Sem 3": ["Arch Design III", "History of Arch I", "Climatology"],
    "Sem 4": ["Arch Design IV", "History of Arch II", "Structural Design I"],
    "Sem 5": ["Arch Design V", "Bldg Services I", "Est & Costing"],
    "Sem 6": ["Arch Design VI", "Bldg Services II", "Town Planning"],
    "Sem 7": ["Arch Design VII", "Advanced Const", "Project Mgt"],
    "Sem 8": ["Professional Practice", "Internship"],
    "Sem 9": ["Practical Training"],
    "Sem 10": ["Thesis"],
  },
  "B.Pharm": {
    "Sem 1": ["Human Anatomy", "Pharm Analysis", "Pharmaceutics I"],
    "Sem 2": ["Pathophysiology", "Biochemistry", "Computer Appl"],
    "Sem 3": ["Org Chem II", "Physical Pharm I", "Microbiology"],
    "Sem 4": ["Org Chem III", "Physical Pharm II", "Pharmacognosy I"],
    "Sem 5": ["Med Chem I", "Pharmacology I", "Jurisprudence"],
    "Sem 6": ["Med Chem II", "Pharmacology II", "Biopharmaceutics"],
    "Sem 7": ["Instr Methods Analysis", "Ind Pharmacy II", "Pharmacy Pract"],
    "Sem 8": ["Biostats", "Social Pharmacy", "Project"],
  },
  "B.Sc Nursing": {
    "Sem 1": ["Anatomy", "Physiology", "Nursing Foundations I"],
    "Sem 2": ["Biochemistry", "Nutrition", "Nursing Foundations II"],
    "Sem 3": ["Microbiology", "Infection Control", "Med-Surg Nursing I"],
    "Sem 4": ["Pharmacology I", "Pathology I", "Med-Surg Nursing II"],
    "Sem 5": ["Child Health Nursing I", "Mental Health Nursing I"],
    "Sem 6": ["Child Health Nursing II", "Mental Health Nursing II"],
    "Sem 7": ["Comm Health Nursing I", "Midwifery I"],
    "Sem 8": ["Comm Health Nursing II", "Midwifery II", "Internship"],
  },
  "B.Ed": {
    "Sem 1": [
      "Childhood & Growing Up",
      "Contemporary India",
      "Language across Comm",
    ],
    "Sem 2": ["Learning & Teaching", "Pedagogy I", "Knowledge & Curr"],
    "Sem 3": ["Pedagogy II", "School Internship Phase I"],
    "Sem 4": [
      "Assessment for Learning",
      "Creating Inclusive Sch",
      "Internship II",
    ],
  },
  "B.Des": {
    "Sem 1": ["Design Fundamentals", "Drawing I", "Color Temp"],
    "Sem 2": ["Typography I", "Drawing II", "Form & Space"],
    "Sem 3": ["Design Thinking", "Material Study", "Photography"],
    "Sem 4": ["Interaction Design I", "Product Des I", "Semiotics"],
    "Sem 5": ["Interaction Design II", "Product Des II", "Research"],
    "Sem 6": ["System Design", "UI/UX", "Prototyping"],
    "Sem 7": ["Advanced Studio", "Portfolio", "Mgt"],
    "Sem 8": ["Final Degree Project"],
  },
};

export default SUBJECTS;
